version: "3.8"

services:
  iallm:
    image: comsatel/iallm:${IMAGE_VERSION:-0.1.0}
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      LLM_MODEL_NAME: "llama-3.2-90b-text-preview" #llama3.2:3b
      LLM_EMBED_MODEL_NAME: "nomic-embed-text" #"nomic-embed-text:v1.5"
      GROQ_API_KEY: ${GROQ_API_KEY:-CHANGEME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./knowledge:/app/src/knowledge:rw"
      - "./instruments:/app/src/instruments:rw"
      - "./memory:/app/src/memory:rw"
